FROM debian:stable-20190228-slim
ENV DEBIAN_FRONTEND noninteractive
ENV MINICONDA_VERSION="4.5.11"
ENV MANTA_VERSION=1.6.0
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

#install packages like in continuumio/miniconda2:4.5.12
RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates bzip2 gcc g++ make python2 zlib1g-dev cmake libboost-all-dev

SHELL ["/bin/bash", "-c","-l"]

RUN wget https://github.com/Illumina/manta/releases/download/v${MANTA_VERSION}/manta-${MANTA_VERSION}.release_src.tar.bz2 && tar -xjf manta-${MANTA_VERSION}.release_src.tar.bz2 && mkdir build && cd build \
&& ../manta-${MANTA_VERSION}.release_src/configure --jobs=4 --prefix=/usr/local && make -j4 install

CMD ["/bin/bash"]
