setwd('/mnt/cold1/snaketree/prj/snakegatk_real/dataset/WES_Marika/mutect')
af <- read.table('merged.table_nomultiallele', header=TRUE, sep="\t", row.names=1)
head(df)
head(af)
aff <- unlist(af[af!=0])
head(aff)
ggplot(data=data.frame(af=aff), aes(x=aff)) + geom_histogram(alpha=0.5, position='dodge')+scale_x_continuous(breaks=(seq(0, 1, by=0.05)))+theme_bw()
waf <- read.table('merged.table_nomultiallele_wtiers', header=TRUE, sep="\t", row.names=1)
aff <- unlist(waf[waf!=0])
ggplot(data=data.frame(af=aff), aes(x=aff)) + geom_histogram(alpha=0.5, position='dodge')+scale_x_continuous(breaks=(seq(0, 1, by=0.05)))+theme_bw()
pdxbin <- ifelse(waf==0,0, 1)
head(pdxbin)
n_muts_x <- colSums(pdxbin)
pd <- data.frame(n_muts=n_muts_x)
head(pd)
ggplot(data=pd, aes(x=af, fill=class)) + geom_histogram(alpha=0.5)+xlab('nmuts')+theme_bw()
ggplot(data=pd, aes(x=n_muts)) + geom_histogram(alpha=0.5)+xlab('nmuts')+theme_bw()
ggplot(data=pd, aes(x=n_muts)) + geom_histogram(alpha=0.5, position="dodge")+xlab('nmuts')+theme_bw()
ggplot(data=pd, aes(x=n_muts)) + geom_histogram(alpha=0.5, position="dodge")+xlab('nmuts')+theme_bw()+theme(text=element_text(size=20))
waf <- read.table('merged.table_nomultiallele_alltiers', header=TRUE, sep="\t", row.names=1)
pdxbin <- ifelse(waf==0,0, 1)
n_muts_x <- colSums(pdxbin)
pd <- data.frame(n_muts=n_muts_x)
ggplot(data=pd, aes(x=n_muts)) + geom_histogram(alpha=0.5, position="dodge")+xlab('nmuts')+theme_bw()+theme(text=element_text(size=20))
